### ISSUE TITLE
姊妹机器的疑惑

### ISSUE THREAD

**Issue by qiqco** [chuonDDS/Dell-Inspiron-7570-Hackintosh#1]
我有一台Inspiron 7370，并且我也在维护它
我在dell官网看到我们两个机器是共用一个BIOS的
而且我们两个都是ALC295，我想知道你的耳机接口正常吗

**Comment by chuonDDS** [comment]
yes my headphone jack is normal but I use ALC PLUG FIX

**Comment by chuonDDS** [comment]
> 我有一台Inspiron 7370，并且我也在维护它
> 我在dell官网看到我们两个机器是共用一个BIOS的
> 而且我们两个都是ALC295，我想知道你的耳机接口正常吗

yes my headphone jack is normal but I use ALC PLUG FIX in my folder HP JACK

**Comment by qiqco** [comment]
> > 我有一台Inspiron 7370，并且我也在维护它
> > 我在dell官网看到我们两个机器是共用一个BIOS的
> > 而且我们两个都是ALC295，我想知道你的耳机接口正常吗
> 
> yes my headphone jack is normal but I use ALC PLUG FIX in my folder HP JACK

请问应该怎么操作呢，🙏

**Comment by qiqco** [comment]
我已经解决了
